[env:m5stack-stamps3]
platform = espressif32
board = m5stack-stamps3
framework = arduino

build_flags = 
	-I include
	-DARDUINO_USB_CDC_ON_BOOT=1 ; Enable USB CDC on boot for serial comms

lib_deps = 
	m5stack/M5Cardputer@^1.1.1
	lvgl/lvgl@^8.3.11
	bblanchon/ArduinoJson@^6.21.2
	tzapu/WiFiManager@^2.0.17
	mathieucarbou/ESPAsyncWebServer@^3.6.0
	fastled/FastLED @ ^3.6.0

monitor_speed = 115200
; Игнорируем ttyS0 и ищем только реальные USB устройства
monitor_port = /dev/ttyACM*